export type GalleryImage = {
  id: string;
  src: string;
  alt: string;
  title: string;
  category: "Exterior" | "Interior" | "Events" | "Floorplan";
  description?: string;
  featured?: boolean;
};

export const galleryImages: GalleryImage[] = [
  {
    id: "ext-showcase-01",
    src: "/images/gallery/gallery-exterior-showcase-01.jpeg",
    alt: "Front showcase view of the Upscale Outhouse luxury bathroom trailer",
    title: "Luxury Trailer Showcase",
    category: "Exterior",
    description: "Our flagship luxury restroom trailer ready for your event.",
    featured: true,
  },
  {
    id: "ext-side-01",
    src: "/images/gallery/gallery-exterior-side-01.jpg",
    alt: "Side profile of the luxury trailer showing clean exterior lines",
    title: "Clean Exterior Lines",
    category: "Exterior",
    description: "Sleek side profile designed to complement any venue.",
  },
  {
    id: "ext-doors-01",
    src: "/images/gallery/gallery-exterior-doors-01.jpg",
    alt: "Entry doors of the luxury bathroom trailer",
    title: "Grand Entry Doors",
    category: "Exterior",
    description: "Welcoming entry with premium hardware and finishes.",
  },
  {
    id: "ext-rear-01",
    src: "/images/gallery/gallery-exterior-rear-01.jpeg",
    alt: "Rear view of the trailer highlighting the premium build quality",
    title: "Premium Build Quality",
    category: "Exterior",
    description: "Built to the highest standards with attention to every detail.",
  },
  {
    id: "ext-night-01",
    src: "/images/gallery/gallery-exterior-night-01.jpg",
    alt: "Luxury trailer illuminated at night with warm ambient lighting",
    title: "Evening Ambiance",
    category: "Exterior",
    description: "Warm LED lighting creates an inviting atmosphere after dark.",
    featured: true,
  },
  {
    id: "int-womens-01",
    src: "/images/gallery/gallery-interior-womens-01.jpg",
    alt: "Elegant women's restroom interior with upscale finishes and vanity mirrors",
    title: "Women's Suite",
    category: "Interior",
    description: "Elegant vanity area with premium mirrors and lighting.",
    featured: true,
  },
  {
    id: "int-doors-01",
    src: "/images/gallery/gallery-interior-doors-01.jpg",
    alt: "Interior door detail showing premium hardware and trim",
    title: "Premium Interior Details",
    category: "Interior",
    description: "Quality hardware and trim throughout.",
  },
  {
    id: "fp-01",
    src: "/images/gallery/gallery-floorplan-01.jpg",
    alt: "Floor plan layout of the luxury bathroom trailer",
    title: "Trailer Floor Plan",
    category: "Floorplan",
    description: "Thoughtfully designed layout maximizing comfort and flow.",
  },
  {
    id: "evt-winery-01",
    src: "/images/gallery/IMG_0873.jpg",
    alt: "Upscale Outhouse trailer at a winery event with roses and string lights",
    title: "Winery Event Setup",
    category: "Events",
    description: "Our trailer at a beautiful winery venue surrounded by roses and string lights.",
    featured: true,
  },
  {
    id: "evt-winery-02",
    src: "/images/gallery/IMG_0874.jpg",
    alt: "Luxury trailer with rose garden and winery venue in background",
    title: "Winery Rose Garden",
    category: "Events",
    description: "Nestled alongside the rose garden at a Central Valley winery.",
  },
  {
    id: "evt-winery-03",
    src: "/images/gallery/IMG_0875.jpg",
    alt: "Front view of trailer with accessible ramp at winery event",
    title: "Accessible Entry",
    category: "Events",
    description: "ADA-accessible ramp deployed at a winery celebration.",
  },
  {
    id: "evt-winery-04",
    src: "/images/gallery/IMG_0876.jpg",
    alt: "Full side profile of trailer with doors and stairs at winery venue",
    title: "Full Trailer at Venue",
    category: "Events",
    description: "Full side profile showing separate entrances at an upscale winery event.",
  },
  {
    id: "evt-winery-05",
    src: "/images/gallery/IMG_0877.jpg",
    alt: "Upscale Outhouse trailer with logo and branding at vineyard event",
    title: "Vineyard Showcase",
    category: "Events",
    description: "Our signature branding on display at a vineyard celebration.",
    featured: true,
  },
  {
    id: "evt-winery-06",
    src: "/images/gallery/evt-winery-evening-front.jpg",
    alt: "Front view of Upscale Outhouse trailer at golden hour with stairs deployed and guests in background",
    title: "Golden Hour at the Winery",
    category: "Events",
    description: "Front view of the trailer with stairs deployed during a bustling winery evening event.",
    featured: true,
  },
  {
    id: "evt-winery-07",
    src: "/images/gallery/evt-winery-sunset-wide.jpg",
    alt: "Wide panoramic view of trailer alongside rose garden with sunset over winery venue",
    title: "Sunset Winery Panorama",
    category: "Events",
    description: "A sweeping view of the trailer set beside a rose garden as the sun sets over the winery.",
  },
  {
    id: "evt-winery-08",
    src: "/images/gallery/evt-winery-pavilion-roses.jpg",
    alt: "Rear view of trailer with winery pavilion and rose garden in the background",
    title: "Pavilion & Rose Garden",
    category: "Events",
    description: "The trailer positioned near the winery pavilion surrounded by a vibrant rose garden.",
  },
  {
    id: "evt-team-01",
    src: "/images/gallery/evt-team-winery.jpg",
    alt: "Upscale Outhouse team members posing together at a winery event",
    title: "The Upscale Outhouse Team",
    category: "Events",
    description: "Our team on-site at a winery event, proud to deliver a premium experience.",
  },
];
